### PR TITLE
Update template for usage with Polymer 2

### PR DESCRIPTION
**Pull request by Mihaiii**

### CODE REVIEW

**Review by alshakero — APPROVED** [review]

**Comment by alshakero** [comment]
Bump

**Comment by Mihaiii** [comment]
I avoided merging this because it didn't got all the requested approvals.
Regarding the referenced issue, please confirm that is 100% safe to remove `<link rel="import" href="/sys/polymer/polymer.html">` so I can make that commit and then merge it directly.

**Comment by alshakero** [comment]
I don't recommend removing Polymer import at all, because:

1. We might remove Polymer from the app-shell. Leaving every view to decide what imports it needs. I.e slightly more atomic views.
2. It's deduped so it doesn't hurt.
3. It gives meaning to `dom-bind`, when you remove Polymer, `dom-bind` will look way more outlandish.

@tomalec agree?

**Comment by Mihaiii** [comment]
Merging.
If it will be decided that `<link rel="import" href="/sys/polymer/polymer.html">` should be removed, please make another PR.

**Pull request merged**
